import {StyleSheet} from 'react-native';
import variables from '../../variables';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignContent: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    margin: 0,
    padding: 10,
  },
  webViewOutterContainer: {
    padding: 0,
    maxHeight: 480,
    paddingTop: 0,
    flex: 1,
    paddingVertical: 0,
    marginTop: 0,
    marginVertical: 0,
    margin: 0,
  },
  webviewContentContainer: {
    width: 300,
    height: 480,
    flex: 1,
    padding: 0,
    paddingTop: 0,
    paddingVertical: 0,
    marginTop: 0,
    marginVertical: 0,
    margin: 0,
    backgroundColor: 'transparent',
    alignContent: 'center',
    justifyContent: 'flex-end',
    alignSelf: 'center',
    alignItems: 'center',
  },
  webview: {
    flex: 1,
    paddingVertical: 0,
    marginTop: -10,
    marginVertical: 0,
    marginBottom: 2,
    margin: 0,
    resizeMode: 'contain',
    display: 'flex',
    textAlign: 'center',
    width: 300,
    height: 480,
    alignContent: 'center',
    justifyContent: 'flex-end',
    alignSelf: 'center',
    alignItems: 'center',
  },
  closeButton: {
    backgroundColor: variables.danger600,
    borderRadius: 8,
    marginTop: 20,
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignSelf: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    fontFamily: variables.nunitoRegular,
    color: variables.defaultWhite,
  },
});
